name: Check For Followers
on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:

jobs:
  boop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: node action.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
