name: Check For Followers
on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:

jobs:
  boop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - run: node action.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache
        uses: actions/cache@v3.0.1
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: node_modules/
          # An explicit key for restoring and saving the cache
          key: npm

