name: issues

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - run:  |
        echo "$ISSUE_BODY" > temp.txt
        cat temp.txt
    
      env: 
        ISSUE_BODY: ${{ github.event.issue.body }}
