name: Metrics
on:
  # Schedule updates (each 12 hour)
  schedule:
  - cron: 0 */12 * * *
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.GH_PAT }}

          # Options
          user: xiaozhu2007
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_activity: yes
          plugin_activity_days: 3
          plugin_activity_filter: all
          plugin_activity_ignored: HelloTools-bot
          plugin_activity_limit: 10
          plugin_activity_load: 300
          plugin_activity_timestamps: yes
          plugin_activity_visibility: public
          plugin_introduction: yes
          plugin_introduction_title: yes
