name: Update README

on:
  push:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          template: "templates/profile.tpl"
          writeTo: "README.md"
      
      - uses: Platane/snk@v2
        with:
            github_user_name: ${{ github.repository_owner }}
            outputs: |
              docs/github-snake.svg
              docs/github-snake.gif
              docs/github-snake-dark.svg?palette=github-dark
              docs/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          commit_message: 'docs: Update generated README [skip ci]'
          branch: main
          commit_user_name: 'HelloTools 机器人'
          commit_user_email: 3356136957@qq.com
          commit_author: HelloTools 机器人 <3356136957@qq.com>
